#!/usr/bin/php

<?php

require 'vendor/autoload.php';
include_once __DIR__ . '/../db.php';

$input = file_get_contents('php://stdin');
//get info
$email = new PlancakeEmailParser($input);

try {
    $conn = new PDO("mysql:host=$servername;dbname=$db", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    //Connected successfully, let's insert
    $sql = "INSERT INTO $table (to_email,subject,body) VALUES (:to,:subject,:body)";
    $q = $conn->prepare($sql);
    $q->bindParam(':to', implode(";",  $email->getTo()));
    $q->bindParam(':subject', $email->getSubject());
    $q->bindParam(':content', $email->getPlainBody());
    $q->execute();
}catch(PDOException $e){
  //future error handling
}